name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: 94.156.116.138
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".next/*,package.json,package-lock.json,ecosystem.config.js,next.config.js,tsconfig.json,src/*,public/*,src/fonts/*,src/styles/*"
        target: "/var/www/ceramica"
        strip_components: 1
        
    - name: Restart application
      uses: appleboy/ssh-action@master
      with:
        host: 94.156.116.138
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/ceramica
          npm ci --production
          pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js 